### ISSUE TITLE
Lettre à la bonne place non affichée

### ISSUE THREAD

**Issue by PLfightX** [Lola-Ackubar/ISN-Stdo-projet-bac-blanc#1]
J'ai eu ce résultat : 
`J1 entre le mot de 7 lettres :  oreille
Mot validé
J2, à toi
Votre proposition (7 lettres) :  esaintu
e......
Votre proposition (7 lettres) :  esiantu
e.i....`
Alors que j'aurais du avoir celui là : 
`J1 entre le mot de 7 lettres :  oreille
Mot validé
J2, à toi
Votre proposition (7 lettres) :  esaintu
e..I...
Votre proposition (7 lettres) :  esiantu
e.i....`

La lettre ne s'affiche donc pas alors qu'elle est à la bonen place et devrais s'afficher en majuscules

**Comment by Lola-Ackubar** [comment]
AH

**Comment by PLfightX** [comment]
J'ai refait un test : 

J1 entre le mot de 7 lettres :  oreille
Mot validé
J2, à toi 
Votre proposition (7 lettres) :  abcidef
...I.e. 
Votre proposition (7 lettres) :  fedicba
.e..... 
Votre proposition (7 lettres) :  fldicba
.l..... 
Votre proposition (7 lettres) :  eorille
eor....
Votre proposition (7 lettres) :  eroille
e.o....
Votre proposition (7 lettres) :  troille
.Ro....

Du coup à partir du moment où il y a déja eu une lettre mal placée, les lettres bien placées ne sont plus prises en compte ... étrange ...

**Comment by PLfightX** [comment]
Le problème vient forcément de cette instruction : 
`reponse[lettre] = propls[lettre].lower()`
Ligne 44
Elle insère un point dans la réponse parce qu'un point a été ajouté dans propls
Mais je sais pas pk le if s'active ...

**Comment by PLfightX** [comment]
Bug résolu en modifiant le caractère d'annulation de . en ! lorsque une lettre est bien placée pour éviter des interférences
